### PR TITLE
fix/extend part number validation in MultiPart methods

### LINKED ISSUE #1031: MultiPartInputFile::header doesn't check for out-of-bounds access
Should it throw Iex::ArgExc? Or at least use `at()`?

https://github.com/AcademySoftwareFoundation/openexr/blob/a00575feb645189354097d9b8808aa3030a800b0/src/lib/OpenEXR/ImfMultiPartInputFile.cpp#L194
```c++
const Header & MultiPartInputFile::header(int n) const { return _data->_headers[n]; }
```

### PR DESCRIPTION
**Pull request by peterhillman**
Fixes #1031
Adds extra bounds checks to MultiPartInputFile and MultiPartOutputFile methods that take part indexes, and fixes an off-by-one in an existing check

Signed-off-by: Peter Hillman <peterh@wetafx.co.nz>

### CODE REVIEW

File: src/lib/OpenEXR/ImfMultiPartInputFile.cpp [hunk 1]
```diff
@@ -186,6 +186,10 @@ template DeepTiledInputFile* MultiPartInputFile::getInputPart<DeepTiledInputFile
 InputPartData*
 MultiPartInputFile::getPart(int partNumber)
 {
+    if(partNumber<0 || partNumber >= _data->_headers.size())
```
Comment (cary-ilm) [inline src/lib/OpenEXR/ImfMultiPartInputFile.cpp]: Is this necessary? Won't the call to getPart(partNumber) below check for a valid partnumber?

**Review by meshula — APPROVED** [review]
It kind of feels like we might benefit from a non-throwing `bool isValidPart(int n);` method and also 'void checkValidPart(int n)` that contains the throw, in order to have only one copy of the checking and reporting logic to maintain

File: src/lib/OpenEXR/ImfMultiPartInputFile.cpp (hunk 1 above)
Comment (peterhillman) [reply src/lib/OpenEXR/ImfMultiPartInputFile.cpp]: Good point. That test is now removed

**Review by meshula — APPROVED** [review]
