### PR TITLE
Fix #452: read floats with 32 bit alignment

### LINKED ISSUE #452: test failure on armv7
````
Running testOptimizedInterleavePatterns
Testing SSE optimisation with different interleave patterns (large images) ... 
 0, 0: RGBHalf read as RGBHalf...                            OK 
 0, 1: RGBHalf read as RGBAHalf...                           OK 
 0, 2: RGBHalf read as ABGRHalf...                           OK 
 0, 3: RGBHalf read as RGBFloat...                           OK 
 0, 4: RGBHalf read as BGRHalf...                            OK 
 0, 5: RGBHalf read as RGBLeftRGB...                         OK 
 0, 6: RGBHalf read as RGBRightRGB...                        OK 
 0, 7: RGBHalf read as RGBALeftRGBA...                       OK 
 0, 8: RGBHalf read as RGBARightRGBA...                      OK 
 0, 9: RGBHalf read as LeftRGB...                            OK 
 0,10: RGBHalf read as RightRGB...                           OK 
 0,11: RGBHalf read as LeftRGBA...                           OK 
 0,12: RGBHalf read as RightRGBA...                          OK 
 0,13: RGBHalf read as TripleView...                         OK 
 0,14: RGBHalf read as Trees...                              OK 
 0,15: RGBHalf read as TreesAndBirds...                      OK 
 0,16: RGBHalf read as RGBLeftRGBA...                        OK 
 0,17: RGBHalf read as RGBRightRGBA...                       OK 
 0,18: RGBHalf read as RGBALeftRGB...                        OK 
 0,19: RGBHalf read as RGBARightRGB...                       OK 
 0,20: RGBHalf read as TwinRGBLeftRGB...                     OK 
 0,21: RGBHalf read as TwinRGBRightRGB...                    OK 
 0,22: RGBHalf read as TwinRGBALeftRGBA...                   OK 
 0,23: RGBHalf read as TwinRGBARightRGBA...                  OK 
 0,24: RGBHalf read as TripleTripleView...                   OK 
 0,25: RGBHalf read as Alpha...                              OK 
 0,26: RGBHalf read as RedAlpha...                           OK 
 0,27: RGBHalf read as RG+BA...                              OK 
 0,28: RGBHalf read as RGBpassiveA...                        OK 
 0,29: RGBHalf read as RGBpassiveleftRGB...                  OK 
 0,30: RGBHalf read as RGBFloatA...                         
````
per the test-suite log above it looks like a crash. Will try to provide more details later.

Fedora Rawhide on armv7, for complete logs please see https://koji.fedoraproject.org/koji/taskinfo?taskID=36319716

### PR DESCRIPTION
**Pull request by peterhillman**
May only be a partial solution: UINTs aren't read aligned, and may cause slower performance on architectures that can read non-32 bit aligned floats

### CODE REVIEW

File: OpenEXR/IlmImfTest/testOptimizedInterleavePatterns.cpp [hunk 1]
```diff
@@ -167,6 +167,14 @@ Schema Schemes[] =
         {NULL,NULL,NULL,0,NULL,NULL}
 };
 
+template<class T> inline T alignToFour(T input)
```
Comment (meshula) [inline OpenEXR/IlmImfTest/testOptimizedInterleavePatterns.cpp:170]: Can bring the cost to basically nothing by doing this
return (input + 3) & ~3

Comment (peterhillman) [reply OpenEXR/IlmImfTest/testOptimizedInterleavePatterns.cpp:170]: OK, I'll update that. I'd not done it that way because I wasn't convinced that would work with 64 bit addresses

Comment (meshula) [reply OpenEXR/IlmImfTest/testOptimizedInterleavePatterns.cpp:170]: Right, might need ~3 for 32 bit and ~3ll for 64

Comment (peterhillman) [reply OpenEXR/IlmImfTest/testOptimizedInterleavePatterns.cpp:170]: I'm not really sure the best way to do robust compile-time detection of 32 vs 64 bit architectures.
Given that this is only in a test, not the main library, and is only called a handful of times, I wonder if it might be safer to leave it as it is?

Comment (kdt3rd) [reply OpenEXR/IlmImfTest/testOptimizedInterleavePatterns.cpp:170]: oh, I would have thought the 3s would be promoted to the appropriate size, but you could be pedantic and say
return r (input + static_cast<uintptr_t>(3)) & ~static_cast<uintptr_t>(3);

**Comment by kdt3rd** [comment]
LGTM, this is test-only code,  simpler is better
