### PR TITLE
Fix issue with unpacked size computation

### LINKED ISSUE #1137: Corruption and failures reading 4:2:0 images using OpenEXRCore
I'm seeing image corruption and errors when decoding subsampled data using OpenEXRCore.

The code below reads a 4:2:0 RY,Y,BY file using OpenEXRCore and with the C++ SDK and compares the results.

Using a 1920x1080 SMTPE bars image, in each compression option (written using the C++ SDK via the ProEXR Photoshop plugin) I see:

Uncompressed - differences in Y channel
RLE - exr_decoding_run (line 1): EXR_ERR_CORRUPT_CHUNK
ZIP - exr_decoding_run (line 1): EXR_ERR_CORRUPT_CHUNK
ZIP16 - decodes match
PIZ - differences in Y channel
PXR24 - decodes match
B44 - decodes match
B44A - decodes match
(DWA untestable because not yet supported in OpenEXRCore)

It's quite possible there's an error in my Core usage but I can't see it.

```
#include <openexr.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include <ImfInputFile.h>
#include <ImfMultiPartInputFile.h>
#include <ImfInputPart.h>
#include <ImfFrameBuffer.h>

int fail(const char *format, ...)
{
    va_list args;
    va_start(args, format);
    vfprintf(stderr, format, args);
    fprintf(stderr, "\n");
    va_end(args);
    return 1;
}

int main(int argc, const char * argv[])
{
    if(argc != 2)
    {
	fprintf(stderr, "Syntax: %s path_to_420.exr\n", argv[0]);
	return 1;
    }

    fprintf(stderr, "Reading %s using OpenEXRCore\n", argv[1]);
    
    exr_context_t m_context {NULL};
    exr_context_initializer_t ctxtinit {0};
    exr_result_t rv = exr_start_read(&m_context, argv[1], &ctxtinit);
    if (rv != EXR_ERR_SUCCESS)
	return fail("exr_start_read: %s", exr_get_error_code_as_string(rv));

    exr_attr_box2i_t datawin;
    exr_get_data_window(m_context, 0, &datawin);

    int m_width  = datawin.max.x - datawin.min.x + 1;
    int m_height = datawin.max.y - datawin.min.y + 1;

    uint8_t * pixmap = new uint8_t[m_width * m_height * 3 * 2];
    memset(pixmap, 0, m_width * m_height * 3 * 2);
    
    int32_t lines_per_chunk;
    exr_get_scanlines_per_chunk(m_context, 0, &lines_per_chunk);

    // We reuse one pipeline as we go
    exr_decode_pipeline_t pipeline = {0};
    
    for (int y = datawin.min.y; y <= datawin.max.y; y += lines_per_chunk)
    {
	exr_chunk_info_t cinfo = { 0 };
	rv = exr_read_scanline_chunk_info (m_context, 0, y, &cinfo);
	if (rv != EXR_ERR_SUCCESS)
	    return fail("exr_read_scanline_chunk_info (part %d y %d): %s", 0, y, exr_get_error_code_as_string(rv));
	
	if(pipeline.channels == NULL)
	{
	    // Setup pipeline the first time we hit it
	    rv = exr_decoding_initialize (m_context, 0, &cinfo, &pipeline);
	    if(rv != EXR_ERR_SUCCESS)
		return fail("exr_decoding_initialize: %s", exr_get_error_code_as_string(rv));

	    for (int c = 0; c < pipeline.channel_count; c++)
	    {
		exr_coding_channel_info_t & outc = pipeline.channels[c];
		outc.user_bytes_per_element = 2;
		outc.user_data_type = EXR_PIXEL_HALF;
		outc.decode_to_ptr = (uint8_t*)0x1000; // in case exr_decoding_choose_default_routines checks for NULL
		if(!strcmp(outc.channel_name, "RY"))
		{
		    outc.user_pixel_stride = 12;
		    outc.user_line_stride = 12 * m_width;
		}
		else if(!strcmp(outc.channel_name, "Y"))
		{
		    outc.user_pixel_stride = 6;
		    outc.user_line_stride = 6 * m_width;
		}
		else if(!strcmp(outc.channel_name, "BY"))
		{
		    outc.user_pixel_stride = 12;
		    outc.user_line_stride = 12 * m_width;
		}
		else
		{
		    // don't want this channel
		    outc.decode_to_ptr = NULL;
		}
	    }
	    rv = exr_decoding_choose_default_routines (m_context, 0, &pipeline);
	    if(rv != EXR_ERR_SUCCESS)
		return fail("exr_decoding_choose_default_routines: %s", exr_get_error_code_as_string(rv));
	}
	else
	{
	    // Reuse existing pipeline
	    rv = exr_decoding_update (m_context, 0, &cinfo, &pipeline);
	    if (rv != EXR_ERR_SUCCESS)
		return fail("exr_decoding_update: %s", exr_get_error_code_as_string(rv));
	}
	
	// Set pixmap pointers for this chunk
	uint8_t * start = pixmap + y * m_width * 6;
	for (int c = 0; c < pipeline.channel_count; c++)
	{
	    exr_coding_channel_info_t & outc = pipeline.channels[c];
	    if(!strcmp(outc.channel_name, "RY"))
		outc.decode_to_ptr = start;
	    else if(!strcmp(outc.channel_name, "Y"))
		outc.decode_to_ptr = start + 2;
	    else if(!strcmp(outc.channel_name, "BY"))
		outc.decode_to_ptr = start + 4;
	}
	    
	rv = exr_decoding_run (m_context, 0, &pipeline);
	if(rv != EXR_ERR_SUCCESS)
	    return fail("exr_decoding_run (line %d): %s", y, exr_get_error_code_as_string(rv));
    }

    exr_decoding_destroy (m_context, &pipeline);
    exr_finish(&m_context);

    fprintf(stderr, "OpenEXRCore read succeeded.\n");

    // Now read the same file using C++ SDK

    fprintf(stderr, "Reading %s using OpenEXR\n", argv[1]);
    
    Imf::MultiPartInputFile file(argv[1]);
    Imf::InputPart part(file, 0);
    Imf::FrameBuffer fb;
    
    char * pixmap2 = new char[m_width * m_height * 3 * 2];
    memset(pixmap2, 0, m_width * m_height * 3 * 2);
		
    fb.insert("RY", Imf::Slice (Imf::HALF, pixmap2, 12, 12 * m_width, 2, 2, 0.0));
    fb.insert("Y", Imf::Slice (Imf::HALF, pixmap2 + 2, 6, 6 * m_width, 1, 1, 0.0));
    fb.insert("BY", Imf::Slice (Imf::HALF, pixmap2 + 4, 12, 12 * m_width, 2, 2, 0.0));
    
    part.setFrameBuffer(fb);
    part.readPixels(datawin.min.y, datawin.max.y);

    fprintf(stderr, "OpenEXR read succeeded.\n");

    int ry_errs = 0, y_errs = 0, by_errs = 0;
    for(int y=0; y<m_height; y++)
	for(int x=0; x<m_width; x++)
	{
	    uint16_t * core = (uint16_t*)(pixmap + m_width * 6 * y + x * 6);
	    uint16_t * cpp = (uint16_t*)(pixmap2 + m_width * 6 * y + x * 6);
	    if(core[0] != cpp[0])
		if(ry_errs++ == 0)
		    fprintf(stderr, "First different RY at (%d,%d)\n", x, y);
	    if(core[1] != cpp[1])
		if(y_errs++ == 0)
		    fprintf(stderr, "First different Y at (%d,%d)\n", x, y);
	    if(core[2] != cpp[2])
		if(by_errs++ == 0)
		    fprintf(stderr, "First different BY at (%d,%d)\n", x, y);
	}

    if(ry_errs + y_errs + by_errs == 0)
	fprintf(stderr, "Decoded images match perfectly\n");
    else
	fprintf(stderr, "Differences in decodes: %d RY, %d Y, %d BY\n", ry_errs, y_errs, by_errs);
    
    return 0;
}
```

### PR DESCRIPTION
**Pull request by kdt3rd**
This was an issue with any compression type that encodes a single
scanline per chunk, the unpacked size would end up incorrect.

Fixes #1137 

Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>

### CODE REVIEW

File: src/lib/OpenEXRCore/parse_header.c [hunk 1]
```diff
@@ -2156,11 +2164,20 @@ internal_exr_compute_chunk_offset_size (struct _internal_exr_part* curpart)
                 cunpsz = 2;
             else
                 cunpsz = 4;
-            unpackedsize +=
-                (cunpsz * (uint64_t) ((w + xsamp - 1) / xsamp) *
-                 (uint64_t) ((linePerChunk + ysamp - 1) / ysamp));
+            cunpsz *= (uint64_t) (w / xsamp);
+            cunpsz *= ((uint64_t) linePerChunk);
```
Comment (meshula) [inline src/lib/OpenEXRCore/parse_header.c]: Extra enclosing parents

File: src/lib/OpenEXRCore/parse_header.c [hunk 2]
```diff
@@ -2073,6 +2073,7 @@ internal_exr_compute_chunk_offset_size (struct _internal_exr_part* curpart)
     const exr_attr_chlist_t* channels     = curpart->channels->chlist;
     uint64_t                 unpackedsize = 0;
     int64_t                  w;
```
Comment (meshula) [inline src/lib/OpenEXRCore/parse_header.c:2075]: I kind of wonder if w should be uint64_t in the first place, rather than casting it a few times through the following code? Or is there another reason to keep it signed earlier in the computation?

Comment (kdt3rd) [reply src/lib/OpenEXRCore/parse_header.c:2075]: well, I kept it signed because the data window is signed, although that is not a great reason

Comment (meshula) [reply src/lib/OpenEXRCore/parse_header.c:2075]: I forget if we allow negative data windows? I remember recently there was discussion around it, and I don't remember how it shook out.

Comment (lgritz) [reply src/lib/OpenEXRCore/parse_header.c:2075]: Yes, of course. That's the only way to have "overscan" pixels.

Comment (meshula) [reply src/lib/OpenEXRCore/parse_header.c:2075]: Right, thanks!

Comment (peterhillman) [reply src/lib/OpenEXRCore/parse_header.c:2075]: min.x and max.x are both allowed to be negative, but max.x cannot be less than min.x, so w could be unsigned.

**Review by meshula — APPROVED** [review]

File: src/lib/OpenEXRCore/parse_header.c (hunk 1 above)
Comment (kdt3rd) [reply src/lib/OpenEXRCore/parse_header.c]: made a cleanup pass
