### PR TITLE
fix memory leaks in exrmultipart

### LINKED ISSUE #1478: memory leak in exrmultipart
The sanitizer shows a memory leak in exrmultipart:

````
% exrmultipart -convert -i src/test/bin/Beachball/singlepart.0001.exr -o /tmp/out.exr
input:
      src/test/bin/Beachball/singlepart.0001.exr
output:
      /tmp/out.exr
override:0

-convert input to EXR2 multipart

=================================================================
==734401==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 8 object(s) allocated from:
    #0 0x7f2e7aa541c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f2e794b4c4a in Imf_3_2::TypedAttribute<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::copy() const /home/cary/src/cary-ilm/openexr/src/lib/OpenEXR/ImfAttribute.h:249

Indirect leak of 512 byte(s) in 8 object(s) allocated from:
    #0 0x7f2e7aa541c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f2e794b1c52 in __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocate(unsigned long, void const*) /usr/include/c++/11/ext/new_allocator.h:127
    #2 0x7f2e794b1c52 in std::allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::allocate(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, unsigned long) /usr/include/c++/11/bits/alloc_traits.h:464
    #3 0x7f2e794b1c52 in std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_allocate(unsigned long) /usr/include/c++/11/bits/stl_vector.h:346
    #4 0x7f2e794b1c52 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_allocate_and_copy<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >(unsigned long, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) /usr/include/c++/11/bits/stl_vector.h:1511
    #5 0x7f2e794b1c52 in std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::operator=(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /usr/include/c++/11/bits/vector.tcc:226
    #6 0x55c5e6f2a91e in __gnu_cxx::new_allocator<Imf_3_2::MultiViewChannelName>::deallocate(Imf_3_2::MultiViewChannelName*, unsigned long) /usr/include/c++/11/ext/new_allocator.h:145
    #7 0x55c5e6f2a91e in std::allocator_traits<std::allocator<Imf_3_2::MultiViewChannelName> >::deallocate(std::allocator<Imf_3_2::MultiViewChannelName>&, Imf_3_2::MultiViewChannelName*, unsigned long) /usr/include/c++/11/bits/alloc_traits.h:496
    #8 0x55c5e6f2a91e in std::_Vector_base<Imf_3_2::MultiViewChannelName, std::allocator<Imf_3_2::MultiViewChannelName> >::_M_deallocate(Imf_3_2::MultiViewChannelName*, unsigned long) /usr/include/c++/11/bits/stl_vector.h:354
    #9 0x55c5e6f2a91e in void std::vector<Imf_3_2::MultiViewChannelName, std::allocator<Imf_3_2::MultiViewChannelName> >::_M_realloc_insert<Imf_3_2::MultiViewChannelName const&>(__gnu_cxx::__normal_iterator<Imf_3_2::MultiViewChannelName*, std::vector<Imf_3_2::MultiViewChannelName, std::allocator<Imf_3_2::MultiViewChannelName> > >, Imf_3_2::MultiViewChannelName const&) /usr/include/c++/11/bits/vector.tcc:500

SUMMARY: AddressSanitizer: 768 byte(s) leaked in 16 allocation(s).
```

### PR DESCRIPTION
**Pull request by antond-weta**
Fixes #1478

### CODE REVIEW

File: src/bin/exrmultipart/exrmultipart.cpp [hunk 1]
```diff
@@ -419,6 +419,8 @@ combine (
 
                 partnums.push_back (j);
             }
+            
+            delete infile;
```
Comment (cary-ilm) [inline src/bin/exrmultipart/exrmultipart.cpp]: I don't think this is correct. `infile` gets added to the `fordelete` vector above, and deleted below, so it shouldn't be leaking.

Is it possible that your other fix resolved the leak itself?

`test_exrmultipart.py` is failing in the CI checks, this is presumably why.

Thanks!

**Review by cary-ilm — CHANGES_REQUESTED** [review]

File: src/bin/exrmultipart/exrmultipart.cpp (hunk 1 above)
Comment (antond-weta) [reply src/bin/exrmultipart/exrmultipart.cpp]: Yes, I'd missed the `fordelete` thing. The actual leak seems to be in the missing `delete` when erasing an attribute.

**Review by cary-ilm — APPROVED** [review]
LGTM, thanks!
